insert into Film (name, genre, producers, main_roles) values ('quis', 'action', 'Hedwig Gunthorpe', 'Carly Gallant'); 
insert into Film (name, genre, producers, main_roles) values ('mauris', 'comedy', 'Nicolas Tidder', 'Ginger Charter'); 
insert into Film (name, genre, producers, main_roles) values ('orci vehicula', 'action', 'Doy Birkett', 'Bastian Deners'); 
insert into Film (name, genre, producers, main_roles) values ('id nulla', 'comedy', 'Giuditta Gerrets', 'Skipton Ganniclifft'); 
insert into Film (name, genre, producers, main_roles) values ('id', 'comedy', 'Gamaliel Knight', 'Lin Beneyto'); 
insert into Film (name, genre, producers, main_roles) values ('nisi nam', 'comedy', 'Lanni Sidey', 'Inglebert Adamov'); 
insert into Film (name, genre, producers, main_roles) values ('mus vivamus vestibulum', 'thriller', 'Heather Allinson', 'Nedi Dyball'); 
insert into Film (name, genre, producers, main_roles) values ('phasellus sit', 'thriller', 'Conni Roddan', 'Danya Couzens'); 
insert into Film (name, genre, producers, main_roles) values ('nec condimentum', 'fantasy', 'Lettie Veitch', 'Casandra Willshear'); 
insert into Film (name, genre, producers, main_roles) values ('in tempus sit', 'comedy', 'Sutherlan Bradmore', 'Willi Mitham'); 
insert into Film (name, genre, producers, main_roles) values ('enim', 'thriller', 'Gwenni Varker', 'Eliza Last'); 
insert into Film (name, genre, producers, main_roles) values ('ut', 'comedy', 'Johna Gumm', 'Kenny Gun'); 
insert into Film (name, genre, producers, main_roles) values ('donec posuere metus', 'thriller', 'Maia Fonquernie', 'Charlean Olliff'); 
insert into Film (name, genre, producers, main_roles) values ('vitae', 'thriller', 'Lorry Wretham', 'Hilde Briar'); 
insert into Film (name, genre, producers, main_roles) values ('lorem quisque ut', 'comedy', 'Gill Wrighton', 'Hurleigh Pawden'); 
insert into Film (name, genre, producers, main_roles) values ('curabitur at ipsum', 'thriller', 'Arin Armsden', 'Cathrine Brandone'); 
insert into Film (name, genre, producers, main_roles) values ('convallis duis consequat', 'thriller', 'Buffy Hartness', 'Rodrick Dosdale'); 
insert into Film (name, genre, producers, main_roles) values ('ac', 'fantasy', 'Shepard Cossington', 'Patsy Torfin'); 
insert into Film (name, genre, producers, main_roles) values ('vulputate', 'fantasy', 'Celestyn Benito', 'Toby Chaddock'); 
insert into Film (name, genre, producers, main_roles) values ('aliquam lacus', 'action', 'Bartolemo Jackson', 'Zena Allport'); 
insert into Film (name, genre, producers, main_roles) values ('sit amet', 'action', 'Bertrando Piolli', 'Lian Garwill'); 
insert into Film (name, genre, producers, main_roles) values ('ut', 'thriller', 'Rubia Parmeter', 'Ottilie Tombling'); 
insert into Film (name, genre, producers, main_roles) values ('nulla nunc', 'thriller', 'Rand McNelly', 'Audy Rustidge'); 
insert into Film (name, genre, producers, main_roles) values ('dictumst aliquam', 'action', 'Cleavland Tichner', 'Tudor Gerber'); 
insert into Film (name, genre, producers, main_roles) values ('sit amet lobortis', 'fantasy', 'Keane Cartmill', 'Etienne MacTrustam'); 

insert into Session (film_id, date_time, price) values (27, '2018-12-15 15:00:00', '414.59');
insert into Session (film_id, date_time, price) values (27, '2018-12-15 15:00:00', '381.69');
insert into Session (film_id, date_time, price) values (19, '2018-12-15 15:00:00', '149.90');
insert into Session (film_id, date_time, price) values (19, '2018-12-15 15:00:00', '126.65');
insert into Session (film_id, date_time, price) values (15, '2018-12-15 15:00:00', '454.77');
insert into Session (film_id, date_time, price) values (27, '2018-12-15 15:00:00', '653.75');
insert into Session (film_id, date_time, price) values (17, '2018-12-15 15:00:00', '19.96');
insert into Session (film_id, date_time, price) values (21, '2018-12-15 15:00:00', '174.63');
insert into Session (film_id, date_time, price) values (16, '2018-12-15 15:00:00', '429.98');
insert into Session (film_id, date_time, price) values (7, '2018-12-15 15:00:00', '81.19');
insert into Session (film_id, date_time, price) values (11, '2018-12-15 15:00:00', '224.27');
insert into Session (film_id, date_time, price) values (24, '2018-12-15 15:00:00', '735.52');
insert into Session (film_id, date_time, price) values (17, '2018-12-15 15:00:00', '980.74');
insert into Session (film_id, date_time, price) values (16, '2018-12-15 15:00:00', '762.55');
insert into Session (film_id, date_time, price) values (5, '2018-12-15 15:00:00', '149.47');
insert into Session (film_id, date_time, price) values (19, '2018-12-15 15:00:00', '615.93');
insert into Session (film_id, date_time, price) values (21, '2018-12-15 15:00:00', '203.56');
insert into Session (film_id, date_time, price) values (18, '2018-12-15 15:00:00', '394.55');
insert into Session (film_id, date_time, price) values (15, '2018-12-15 15:00:00', '162.37');
insert into Session (film_id, date_time, price) values (2, '2018-12-15 15:00:00', '85.66');
insert into Session (film_id, date_time, price) values (6, '2018-12-15 15:00:00', '919.89');
insert into Session (film_id, date_time, price) values (6, '2018-12-15 15:00:00', '887.04');
insert into Session (film_id, date_time, price) values (9, '2018-12-15 15:00:00', '428.55');
insert into Session (film_id, date_time, price) values (10, '2018-12-15 15:00:00', '310.37');
insert into Session (film_id, date_time, price) values (26, '2018-12-15 15:00:00', '612.74');

insert into Basket (user_id, session_id) values (4, 2);
insert into Basket (user_id, session_id) values (3, 17);
insert into Basket (user_id, session_id) values (5, 4);
insert into Basket (user_id, session_id) values (4, 14);
insert into Basket (user_id, session_id) values (2, 12);
insert into Basket (user_id, session_id) values (2, 15);
insert into Basket (user_id, session_id) values (3, 3);
insert into Basket (user_id, session_id) values (5, 10);
insert into Basket (user_id, session_id) values (4, 13);
insert into Basket (user_id, session_id) values (3, 16);
insert into Basket (user_id, session_id) values (2, 21);
insert into Basket (user_id, session_id) values (3, 16);
insert into Basket (user_id, session_id) values (4, 11);
insert into Basket (user_id, session_id) values (4, 24);
insert into Basket (user_id, session_id) values (3, 1);
insert into Basket (user_id, session_id) values (2, 6);
insert into Basket (user_id, session_id) values (5, 2);
insert into Basket (user_id, session_id) values (5, 10);
insert into Basket (user_id, session_id) values (2, 5);
insert into Basket (user_id, session_id) values (3, 16);
insert into Basket (user_id, session_id) values (2, 8);
insert into Basket (user_id, session_id) values (3, 5);
insert into Basket (user_id, session_id) values (3, 2);
insert into Basket (user_id, session_id) values (2, 4);

insert into Ticket (user_id, session_id) values (4, 11);
insert into Ticket (user_id, session_id) values (3, 6);
insert into Ticket (user_id, session_id) values (3, 13);
insert into Ticket (user_id, session_id) values (5, 15);
insert into Ticket (user_id, session_id) values (3, 23);
insert into Ticket (user_id, session_id) values (2, 17);
insert into Ticket (user_id, session_id) values (2, 3);
insert into Ticket (user_id, session_id) values (5, 24);
insert into Ticket (user_id, session_id) values (5, 2);
insert into Ticket (user_id, session_id) values (2, 1);
insert into Ticket (user_id, session_id) values (4, 8);
insert into Ticket (user_id, session_id) values (3, 12);
insert into Ticket (user_id, session_id) values (2, 15);
insert into Ticket (user_id, session_id) values (3, 5);
insert into Ticket (user_id, session_id) values (3, 8);
insert into Ticket (user_id, session_id) values (4, 2);
insert into Ticket (user_id, session_id) values (3, 4);
insert into Ticket (user_id, session_id) values (5, 5);
insert into Ticket (user_id, session_id) values (4, 14);
insert into Ticket (user_id, session_id) values (2, 23);
insert into Ticket (user_id, session_id) values (5, 23);
insert into Ticket (user_id, session_id) values (2, 9);
insert into Ticket (user_id, session_id) values (4, 1);
insert into Ticket (user_id, session_id) values (2, 8);


